### PR TITLE
Support AWS Provider V5

### PR DESCRIPTION
**Pull request by max-lobur**
## what

Support AWS Provider V5
Linter fixes

## why

Maintenance

## references

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

### CODE REVIEW

**Comment by jleeingle** [comment]
In AWS provider V5, they introduced a breaking change that would be relevant to this module:

`resource/aws_db_proxy_target: Configurations that define db_instance_identifier using the id attribute of aws_db_instance must be updated to use identifier instead - for example, db_instance_identifier = aws_db_instance.example.id must be updated to db_instance_identifier = aws_db_instance.example.identifier`

I don't believe this MR includes that change?

**Comment by justinkwanlee** [comment]
In AWS provider V5, they introduced a breaking change that would be relevant to this module:

`resource/aws_db_proxy_target: Configurations that define db_instance_identifier using the id attribute of aws_db_instance must be updated to use identifier instead - for example, db_instance_identifier = aws_db_instance.example.id must be updated to db_instance_identifier = aws_db_instance.example.identifier`

I don't believe this PR includes that change?

**Comment by hans-d** [comment]
@max-lobur can you follow up on this, or should we close it?

**Pull request closed without merging**
