### PR TITLE
Updated release to the latest release in example

### PR DESCRIPTION
**Pull request by ghyonathan**
## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

### CODE REVIEW

**Review by Gowiem — COMMENTED** [review]
@ghyonathan thanks for the docs fix -- This small stuff is always appreciated. 

Mind if I ask you to change one thing? We typically point the docs at no version as is shown here: https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/README.yaml#L115-L116

That way we don't need to continually update that version as we upgrade. 

Do you mind changing this module's readme to follow that pattern?

**Comment by ghyonathan** [comment]
> @ghyonathan thanks for the docs fix -- This small stuff is always appreciated.
> 
> Mind if I ask you to change one thing? We typically point the docs at no version as is shown here: https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/master/README.yaml#L115-L116
> 
> That way we don't need to continually update that version as we upgrade.
> 
> Do you mind changing this module's readme to follow that pattern?

Done.

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
Thanks @ghyonathan -- This won't get a release, but we always appreciate the small docs fixes!

**Pull request merged**
